teams = {
    "MLB": {
        "Baltimore Orioles": "1",
        "Boston Red Sox": "2",
        "Los Angeles Angels": "3",
        "Chicago White Sox": "4",
        "Cleveland Indians": "5",
        "Detroit Tigers": "6",
        "Kansas City Royals": "7",
        "Milwaukee Brewers": "8",
        "Minnesota Twins": "9",
        "New York Yankees": "10",
        "Oakland Athletics": "11",
        "Seattle Mariners": "12",
        "Texas Rangers": "13",
        "Toronto Blue Jays": "14",
        "Atlanta Braves": "15",
        "Chicago Cubs": "16",
        "Cincinnati Reds": "17",
        "Houston Astros": "18",
        "Los Angeles Dodgers": "19",
        "Washington Nationals": "20",
        "New York Mets": "21",
        "Philadelphia Phillies": "22",
        "Pittsburgh Pirates": "23",
        "St. Louis Cardinals": "24",
        "San Diego Padres": "25",
        "San Francisco Giants": "26",
        "Colorado Rockies": "27",
        "Miami Marlins": "28",
        "Arizona Diamondbacks": "29",
        "Tampa Bay Rays": "30"
    },
    "NBA": {
        "Atlanta Hawks": "1",
        "Boston Celtics": "2",
        "New Orleans Pelicans": "3",
        "Chicago Bulls": "4",
        "Cleveland Cavaliers": "5",
        "Dallas Mavericks": "6",
        "Denver Nuggets": "7",
        "Detroit Pistons": "8",
        "Golden State Warriors": "9",
        "Houston Rockets": "10",
        "Indiana Pacers": "11",
        "Los Angeles Clippers": "12",
        "Los Angeles Lakers": "13",
        "Miami Heat": "14",
        "Milwaukee Bucks": "15",
        "Minnesota Timberwolves": "16",
        "Brooklyn Nets": "17",
        "New York Knicks": "18",
        "Orlando Magic": "19",
        "Philadelphia 76ers": "20",
        "Phoenix Suns": "21",
        "Portland Trail Blazers": "22",
        "Sacramento Kings": "23",
        "San Antonio Spurs": "24",
        "Oklahoma City Thunder": "25",
        "Utah Jazz": "26",
        "Washington Wizards": "27",
        "Toronto Raptors": "28",
        "Memphis Grizzlies": "29",
        "Charlotte Hornets": "30"
    },
    "NFL": {
        "Atlanta Falcons": "1",
        "Buffalo Bills": "2",
        "Chicago Bears": "3",
        "Cincinnati Bengals": "4",
        "Cleveland Browns": "5",
        "Dallas Cowboys": "6",
        "Denver Broncos": "7",
        "Detroit Lions": "8",
        "Green Bay Packers": "9",
        "Tennessee Titans": "10",
        "Indianapolis Colts": "11",
        "Kansas City Chiefs": "12",
        "Las Vegas Raiders": "13",
        "Los Angeles Rams": "14",
        "Miami Dolphins": "15",
        "Minnesota Vikings": "16",
        "New England Patriots": "17",
        "New Orleans Saints": "18",
        "New York Giants": "19",
        "New York Jets": "20",
        "Philadelphia Eagles": "21",
        "Arizona Cardinals": "22",
        "Pittsburgh Steelers": "23",
        "Los Angeles Chargers": "24",
        "San Francisco 49ers": "25",
        "Seattle Seahwks": "26",
        "Tampa Bay Buccaneers": "27",
        "Washington Football Team": "28",
        "Carolina Panthers": "29",
        "Jacksonville Jaguars": "30",
        "Baltimore Ravens": "33",
        "Houston Texans": "34"
    },
    "NHL": {
        "Boston Bruins": "1",
        "Buffalo Sabres": "2",
        "Calgary Flames": "3",
        "Chicago Blackhawks": "4",
        "Detroit Red Wings": "5",
        "Edmonton Oilers": "6",
        "Carolina Hurricanes": "7",
        "Los Angeles Kings": "8",
        "Dallas Stars": "9",
        "Montreal Canadiens": "10",
        "New Jersey Devils": "11",
        "New York Islanders": "12",
        "New York Rangers": "13",
        "Ottawa Senators": "14",
        "Philadelphia Flyers": "15",
        "Pittsburgh Penguins": "16",
        "Colorado Avalanche": "17",
        "San Jose Sharks": "18",
        "St. Louis Blues": "19",
        "Tampa Bay Lightning": "20",
        "Toronto Maple Leafs": "21",
        "Vancouver Canucks": "22",
        "Washington Capitals": "23",
        "Arizona Coyotes": "24",
        "Anaheim Ducks": "25",
        "Florida Panthers": "26",
        "Nashville Predators": "27",
        "Winnipeg Jets": "28",
        "Columbus Blue Jackets": "29",
        "Minnesota Wild": "30",
        "Las Vegas Golden Knights": "37"
    },
    "NCAAB": {
        "Illinois Fighting Illini": "356",
        "Iowa Hawkeyes": "2294",
        "Indiana Hoosiers": "84",
        "Penn State Nittany Lions": "213",
        "Nebraska Cornhuskers": "158",
        "Michigan State Spartans": "127",
        "Rutgers Scarlett Knights": "164",
        "Ohio State Buckeyes": "194",
        "Northwestern Wildcats": "77",
        "Purdue Boilermakers": "2509",
        "Wisconsin Badgers": "275",
        "Maryland Terrapins": "120",
        "Minnesota Golden Gophers": "135",
        "Michigan Wolverines": "130",
        "Baylor Bears": "239",
        "Kansas Jayhawks": "2305",
        "Texas Longhorns": "251",
        "West Virginia Mountaineers": "277",
        "Oklahoma State Cowboys": "197",
        "Texas Tech Red Raiders": "2641",
        "Oklahoma Sooners": "201",
        "Texas Christian Horned Frogs": "2628",
        "Kansas State Wildcats": "2306",
        "Iowa State Cyclones": "66",
        "Oregon Ducks": "2483",
        "USC Trojans": "30",
        "Colorado Buffaloes": "38",
        "UCLA Bruins": "26",
        "Arizona Wildcats": "12",
        "Oregon State Beavers": "204",
        "Stanford Cardinal": "24",
        "Utah Utes": "254",
        "Arizona State Sun Devils": "9",
        "Washington State Cougars": "265",
        "Washington Huskies": "264",
        "California Golden Bears": "25",
        "Alabama Crimson Tide": "333",
        "Arkansas Razorbacks": "8",
        "LSU Tigers": "99",
        "Tennessee Volunteers": "2633",
        "Florida Gators": "57",
        "Ole Miss Rebels": "145",
        "Missouri Tigers": "142",
        "Kentucky Wildcats": "96",
        "Mississippi State Bulldogs": "344",
        "Georgia Bulldogs": "61",
        "Auburn Tigers": "2",
        "South Carolina Gamecocks": "2579",
        "Texas A&M Aggies": "245",
        "Vanderbilt Commodores": "238",
        "Virginia Cavaliers": "258",
        "Florida State Seminoles": "52",
        "Virginia Tech Hokies": "259",
        "Georgia Tech Yellow Jackets": "59",
        "Clemson Tigers": "228",
        "North Carolina Tar Heels": "153",
        "Louisville Cardinals": "97",
        "Syracuse Orange": "183",
        "North Carolina State Wolfpack": "152",
        "Duke Blue Devils": "150",
        "Notre Dame Fighting Irish": "87",
        "Pittsburgh Panthers": "221",
        "Miami Hurricanes": "2390",
        "Wake Forest Deamon Deacons": "154",
        "Boston College Eagles": "103",
        "Villanova Wildcats": "222",
        "Creighton Bluejays ": "156",
        "Connecticut Huskies": "41",
        "St. Johns Red Storm": "2599",
        "Seton Hall Pirates": "2550",
        "Providence Friars": "2507",
        "Xavier Muskateers": "2752",
        "Georgetown Hoyas": "46",
        "Marquette Golden Eagles": "269",
        "Butler Bulldogs": "2086",
        "DePaul Blue Deamons": "305",
        "Memphis Tigers": "235",
        "SMU Mustangs": "2567",
        "Cincinnati Bearcats": "2132",
        "UCF Knights": "2116",
        "Tulsa Golden Hurricane": "202",
        "South Florida Bulls": "58",
        "Temple Owls": "218",
        "Tulane Green Wave": "2655",
        "East Carolina Buccaneers": "151",
        "Wichita State Shockers": "2724",
        "Houston Cougars": "248",
        "Loyola Chicago Ramblers": "2350",
        "San Diego State Aztecs": "21",
        "Gonzaga Bulldogs": "2250",
        "Drake Bulldogs": "2181",
        "Ohio Bobcats": "195",
        "VCU Rams": "2670",
        "Utah State Aggies": "328",
        "BYU Cougars": "252",
        "Dayton Flyers": "2168",
        "Saint Mary's Gaels": "2608",
        "UNLV Runnin' Rebels": "2439"
    },
    "NCAAF": {
        "Illinois Fighting Illini": "356",
        "Iowa Hawkeyes": "2294",
        "Indiana Hoosiers": "84",
        "Penn State Nittany Lions": "213",
        "Nebraska Cornhuskers": "158",
        "Michigan State Spartans": "127",
        "Rutgers Scarlett Knights": "164",
        "Ohio State Buckeyes": "194",
        "Northwestern Wildcats": "77",
        "Purdue Boilermakers": "2509",
        "Wisconsin Badgers": "275",
        "Maryland Terrapins": "120",
        "Minnesota Golden Gophers": "135",
        "Michigan Wolverines": "130",
        "Baylor Bears": "239",
        "Kansas Jayhawks": "2305",
        "Texas Longhorns": "251",
        "West Virginia Mountaineers": "277",
        "Oklahoma State Cowboys": "197",
        "Texas Tech Red Raiders": "2641",
        "Oklahoma Sooners": "201",
        "Texas Christian Horned Frogs": "2628",
        "Kansas State Wildcats": "2306",
        "Iowa State Cyclones": "66",
        "Oregon Ducks": "2483",
        "USC Trojans": "30",
        "Colorado Buffaloes": "38",
        "UCLA Bruins": "26",
        "Arizona Wildcats": "12",
        "Oregon State Beavers": "204",
        "Stanford Cardinal": "24",
        "Utah Utes": "254",
        "Arizona State Sun Devils": "9",
        "Washington State Cougars": "265",
        "Washington Huskies": "264",
        "California Golden Bears": "25",
        "Alabama Crimson Tide": "333",
        "Arkansas Razorbacks": "8",
        "LSU Tigers": "99",
        "Tennesse Volunteers": "2633",
        "Florida Gators": "57",
        "Ole Miss Rebels": "145",
        "Missouri Tigers": "142",
        "Kentucky Wildcats": "96",
        "Mississippi State Bulldogs": "344",
        "Georgia Bulldogs": "61",
        "Auburn Tigers": "2",
        "South Carolina Gamecocks": "2579",
        "Texas A&M Aggies": "245",
        "Vanderbilt Commodores": "238",
        "Virginia Cavaliers": "258",
        "Florida State Seminoles": "52",
        "Virginia Tech Hokies": "259",
        "Georgia Tech Yellow Jackets": "59",
        "Clemson Tigers": "228",
        "North Carolina Tar Heels": "153",
        "Louisville Cardinals": "97",
        "Syracuse Orange": "183",
        "North Carolina State Wolfpack": "152",
        "Duke Blue Devils": "150",
        "Notre Dame Fighting Irish": "87",
        "Pittsburgh Panthers": "221",
        "Miami Hurricanes": "2390",
        "Wake Forest Deamon Deacons": "154",
        "Boston College Eagles": "103",
        "Memphis Tigers": "235",
        "SMU Mustangs": "2567",
        "Cincinnati Bearcats": "2132",
        "UCF Knights": "2116",
        "Tulsa Golden Hurricane": "202",
        "South Florida Bulls": "58",
        "Temple Owls": "218",
        "Tulane Green Wave": "2655",
        "East Carolina Buccaneers": "151",
        "Wichita State Shockers": "2724",
        "Houston Cougars": "248"
    },
    "Premier-League": {
        "Manchester City" : "382",
        "Manchester United": "360",
        "Leicester City": "375",
        "Chelsea": "363",
        "West Ham United": "371",
        "Liverpool": "364",
        "Tottenham Hotspur": "367",
        "Everton": "368",
        "Leeds United": "357",
        "Arsenal": "359",
        "Aston Villa": "362",
        "Wolverhamptom": "380",
        "Crystal Palace": "384",
        "Burnley": "379",
        "Southampton": "376",
        "Newcastle United": "361",
        "Brighton and Hove Albion": "331",
        "Fulham": "370",
        "West Bromwich Albion": "383",
        "Sheffield United": "398"
    },
    "La-Liga": {
        "FC Barcelona": "83",
        "Real Madrid": "86",
        "Atletico de Madrid": "1068",
        "Sevilla": "243",
        "Real Sociedad": "89",
        "Real Betis": "244",
        "Villareal": "102",
        "Granada CF": "3747",
        "Osasuna": "97",
        "Athletic Bilbao": "93",
        "Celta de Vigo": "85",
        "Levante": "1538",
        "Cadiz": "3842",
        "Valencia CF": "94",
        "Getafe": "2922",
        "Alaves": "96",
        "Elche": "3751",
        "Real Valladolid": "95",
        "Huesca": "5413",
        "Eibar": "3752"
    },
    "Bundesliga": {
        "Bayern Munich": "132",
        "RB Leipzig": "11420",
        "VFL Wolfsburg": "138",
        "Eintracht Frankfurt": "125",
        "Borussia Dortmund": "124",
        "Bayer 04 Leverkusen": "131",
        "FC Union Berlin": "598",
        "Borussia Monchengladbach": "268",
        "Sport-Club Freiburg": "126",
        "VFG Stuttgart": "134",
        "TSG Hoffenheim": "7911",
        "FSV Mainz 05": "2950",
        "FC Augsburg": "3841",
        "SV Werder Bremen": "137",
        "DSC Arminia Bielefeld": "2506",
        "FC Koln": "122",
        "Hertha BSC": "129",
        "FC Schalke": "134"
    },
    "Serie-A": {
        "Inter Milan": "110",
        "AC Milan": "103",
        "Juventus": "111",
        "Atalanta": "105",
        "Napoli": "114",
        "Lazio": "112",
        "AS Roma": "104",
        "Sassuolo": "3997",
        "Sampdoria": "2734",
        "Hellas Verona": "119",
        "Udinese": "118",
        "Bologna": "107",
        "Genoa:": "3263",
        "Fiorentina": "109",
        "Spezia": "4056",
        "Torino": "239",
        "Benevento": "4050",
        "Cagliari": "2925",
        "Parma": "115",
        "Crotone": "3173"
    },
    "Ligue-1": {
        "Paris Saint Germain": "160",
        "AS Monaco": "174",
        "Lille": "166",
        "Lyon": "167",
        "Lens": "175",
        "Marseille": "176",
        "Rennes": "169",
        "Montpellier": "274",
        "Nice": "2502",
        "Metz": "177",
        "Reims": "3243",
        "Angers": "7868",
        "Brest": "6997",
        "St. Etienne": "178",
        "Strasbourg": "180",
        "Bordeaux": "159",
        "Lorient": "273",
        "Nantes": "165",
        "Nimes": "7730",
        "Dijon": "3170"
    },
    "MLS": {
        "Atlanta United": "18418",
        "Austin FC": "20906",
        "Chicago Fire FC": "182",
        "FC Cincinnati": "18267",
        "Colorado Rapids": "184",
        "Columbus Crew SC": "183",
        "D.C. United": "193",
        "FC Dallas": "185",
        "Houston Dynamo FC": "6077",
        "Sporting Kansas City": "186",
        "LA Galaxy": "187",
        "LA FC": "18966",
        "Inter Miami CF": "20232",
        "Minnesota United": "17362",
        "CF Montreal": "9720",
        "Nasvhille SC": "18986",
        "New England Revolution": "189",
        "New York Red Bulls": "190",
        "New York City FC": "17606",
        "Orlando City": "12011",
        "Philadelphia Union": "10739",
        "Portland Timbers": "9723",
        "Real Salt Lake": "4711",
        "San Jose Earthquakes": "191",
        "Seattle Sounders FC": "9726",
        "Toronto FC": "7318",
        "Vancouver Whitecaps FC": "9727"
    }
}
